name: efzerhole
version: 1
handle:
- compress: if ( out_header["Content-Length"] >= 10000 ) compress
- errordoc: 404 /index.php
- passwdaccess:  if(path ~ "/admin/") passwd "admin:admin"
cron:
- description: Check and refresh Access Token for RenRen every 15 days
  url: /cron/renren.php
  schedule: "0 3 */15 * *"
  timezone: Beijing