language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3

dist: trusty
sudo: true

before_script:
    - composer self-update
    - composer install --no-interaction --dev

script:
    - ./vendor/bin/phpunit --verbose --coverage-clover=coverage.xml

after_script:
    - bash <(curl -s https://codecov.io/bash)

after_failure:
    - curl "https://api.day.app/${API_URL_TOKEN}/think-soar-构建失败?url=https://travis-ci.org/guanguans/think-soar/builds"

after_success:
    - curl "https://api.day.app/${API_CONTENT_TOKEN}/think-soar-构建成功"

notifications:
    email: false

matrix:
    fast_finish: true