bluehouseapp_backend:
    resource: @BluehouseappWebBundle/Resources/config/routing/backend/admin/routing_admin.yml
    prefix: /admin


bluehouseapp_manager:
    resource: @BluehouseappWebBundle/Resources/config/routing/backend/manager/routing_manager.yml
    prefix: /manager