dist: bionic
language: generic
os: linux

jobs:
  include:
    - env: PHP_VERSION=7.4 SWOOLE_VERSION="v4.5.5" INSTALL_REDIS_EXT=true DISABLE_XDEBUG=false
      os: osx
      osx_image: xcode12
    - php: "7.1"
      language: php
      env: SWOOLE_VERSION="v4.5.5"
    - php: "7.2"
      language: php
      env: SWOOLE_VERSION="v4.5.5"
    - php: "7.3"
      language: php
      env: SWOOLE_VERSION="v4.5.5"
    - php: "7.4"
      language: php
      env: SWOOLE_VERSION="v4.5.5"
    - php: "7.1"
      language: php
      env: SWOOLE_VERSION="v4.4.21"
    - php: "7.2"
      language: php
      env: SWOOLE_VERSION="v4.4.21"
    - php: "7.3"
      language: php
      env: SWOOLE_VERSION="v4.4.21"
    - php: "7.4"
      language: php
      env: SWOOLE_VERSION="v4.4.21"
    - php: "7.1"
      language: php
      env: SWOOLE_VERSION="v4.3.6"
    - php: "7.2"
      language: php
      env: SWOOLE_VERSION="v4.3.6"
    - php: "7.3"
      language: php
      env: SWOOLE_VERSION="v4.3.6"
    - php: "7.1"
      language: php
      env: SWOOLE_VERSION="master"
    - php: "7.2"
      language: php
      env: SWOOLE_VERSION="master"
    - php: "7.3"
      language: php
      env: SWOOLE_VERSION="master"
    - php: "7.4"
      language: php
      env: SWOOLE_VERSION="master"
    - php: "nightly"
      language: php
      env: SWOOLE_VERSION="master" DISABLE_XDEBUG=false INSTALL_REDIS_EXT=develop DOWNLOAD_PHPUNIT=nightly
  allow_failures:
    - env: SWOOLE_VERSION="master"
    - php: nightly

services:
  - redis
  - mysql

addons:
  apt:
    packages:
      - unzip
  homebrew:
    packages:
      - redis
      - mysql

install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
    brew services start redis;
    brew services start mysql;
    brew install php@$PHP_VERSION;
    brew link --force --overwrite php@$PHP_VERSION;
    PHP_INI_FILE="/usr/local/etc/php/$PHP_VERSION/php.ini";
    macosSwooleMakeArg="--with-openssl-dir=$(brew --prefix openssl)";
    curl -o composer.phar https://getcomposer.org/composer-stable.phar && chmod +x composer.phar && sudo mv -f composer.phar /usr/local/bin/composer && composer -V;
    fi
  - if [[ $TRAVIS_OS_NAME == linux ]]; then
    dd if=/dev/zero of=swap bs=1024 count=2048000 && chmod 600 swap && sudo mkswap swap && sudo swapon swap;
    fi
  - if [[ $INSTALL_REDIS_EXT == "" ]]; then
    EXTENSION_ENABLE_REDIS=1;
    else
    if [[ $INSTALL_REDIS_EXT == true ]]; then
    echo "no" | pecl install -f redis;
    else
    wget https://github.com/phpredis/phpredis/archive/$INSTALL_REDIS_EXT.tar.gz -O redis.tar.gz && mkdir -p redis && tar -xf redis.tar.gz -C redis --strip-components=1 && cd redis && phpize && ./configure && make -j && make install && cd -;
    EXTENSION_ENABLE_REDIS=1;
    fi;
    fi;
    if [[ $EXTENSION_ENABLE_REDIS ]]; then
    if [[ $TRAVIS_OS_NAME == linux ]]; then
    phpenv config-add .travis/redis.ini;
    else
    echo "extension = redis.so" >> $PHP_INI_FILE;
    fi;
    fi;
    php --ri redis;
  - wget https://github.com/swoole/swoole-src/archive/$SWOOLE_VERSION.tar.gz -O swoole.tar.gz && mkdir -p swoole && tar -xf swoole.tar.gz -C swoole --strip-components=1 && cd swoole && phpize && ./configure --enable-openssl --enable-http2 --enable-mysqlnd $macosSwooleMakeArg && make -j && make install && cd -;
    if [[ $TRAVIS_OS_NAME == linux ]]; then
    phpenv config-add .travis/swoole.ini;
    else
    echo "extension = swoole.so" >> $PHP_INI_FILE;
    fi;
    php --ri swoole;
  - php -v && php -m;
  - if [[ $DOWNLOAD_PHPUNIT != "" ]]; then
    curl -sSfL -o ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-$DOWNLOAD_PHPUNIT.phar && php ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit --version && export TEST_PHPUNIT_PATH=~/.phpenv/versions/$(phpenv version-name)/bin/phpunit;
    php ./.travis/composer-no-phpunit.php;
    fi

before_script:
  - if [[ $DISABLE_XDEBUG != false ]]; then
    phpenv config-rm xdebug.ini;
    fi
  - composer update && cd ./tests && composer update && cd ../
  - sh tests/db/install-db.sh

script:
  - ./tests/run

after_failure:
  - php ./.travis/output-server-log.php

env:
  global:
    - MYSQL_SERVER_USERNAME: root
    - MYSQL_SERVER_PASSWORD:
    - HOMEBREW_NO_AUTO_UPDATE: "true"
