name: 918s
version: 1
handle:
- rewrite: if(!is_dir() && !is_file() && path ~ "/") goto "/index.php?%{QUERY_STRING}"
- expire: if(path ~ ".js$") time 8640000
- expire: if(path ~ ".css$") time 8640000
- compress:  if(out_header["Content-Type"] == "text/html") compress
- compress:  if ( out_header["Content-type"] ~ "text/css" ) compress
- compress:  if ( out_header["Content-type"] ~ "text/javascript" ) compress
- compress:  if ( out_header["Content-type"] ~ "application/octet-stream" ) compress
- compress:  if ( out_header["Content-type"] ~ "image/jpeg" ) compress
- compress:  if ( out_header["Content-type"] ~ "image/png" ) compress
- compress:  if ( out_header["Content-type"] ~ "image/pjpeg" ) compress
- compress:  if ( out_header["Content-type"] ~ "image/gif" ) compress
- compress:  if ( out_header["Content-type"] ~ "image/bmp" ) compress
- compress:  if ( out_header["Content-type"] ~ "text/html" ) compress