framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

            failed: 'doctrine://default?queue_name=failed'
#            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            sync: 'sync://'

            # 设置异步优先级
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 1000
                options:
                    queue_name: high

            async_priority_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 1000
                options:
                    queue_name: low

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
#            'App\Message\BuildApiUpdateLog': async
#            'App\Message\BuildDocumentRedisData': async

