vich_uploader:
    db_driver: orm
    mappings:
        info_logo:
            uri_prefix: /backend/info/logo
            upload_destination: '%kernel.project_dir%/public/backend/info/logo'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        admin_user_avatar:
            uri_prefix: /backend/admin_user/avatar
            upload_destination: '%kernel.project_dir%/public/backend/admin_user/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
