filter:
    excluded_paths:
        - tests/*

checks:
    php:
        code_rating: true

tools:
    external_code_coverage: false
    php_analyzer: true
    php_changetracking: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_cpd: true
    php_mess_detector: true
    php_pdepend: true
    sensiolabs_security_checker: true
build:
    environment:
        php:
            version: 7.1
    tests:
        before:
            - 'composer install'
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=test_result'
                coverage:
                    file: 'test_result'
                    format: 'clover'