rootPageId: 1
base: /
baseVariants: {  }
languages:
  -
    title: chinese
    enabled: true
    languageId: '0'
    base: /
    typo3Language: ch
    locale: en_ZH.UTF-8
    iso-639-1: zh
    navigationTitle: ''
    hreflang: ''
    direction: ''
    flag: ch
errorHandling: {  }
routes: {  }
routeEnhancers:
  PageTypeSuffix:
    type: PageType
#    default: '.html'
    map:
      '.html': 0
  NewsPlugin:
      type: Extbase
      #limitToPages: 4
      extension: News
      plugin: Pi1
      routes:
        - { routePath: '/page/{page}', _controller: 'News::list', _arguments: {'page': '@widget_0/currentPage'} }
        - { routePath: '/tag-{tag_name}', _controller: 'News::list', _arguments: {'tag_name': 'overwriteDemand/tags'}}
        - { routePath: '/{news_title}', _controller: 'News::detail', _arguments: {'news_title': 'news'} }
        - { routePath: '/news/{year}/{month}', _controller: 'News::archive' }
      defaultController: 'News::list'
      aspects:
        news_title:
          type: PersistedAliasMapper
          tableName: 'tx_news_domain_model_news'
          routeFieldName: 'title'
          #routeFieldPattern: '^(?P<path_segment>.+)$'          
          #routeFieldName: path_segment      
          #routeValuePrefix: '/'
      defaults:
        page: '0'
      requirements:
        page: '\d+'
disableStaticFileCache: false
