bluehouseapp_banedIPs_index:
    pattern:     /index.{_format}
    defaults:
      _controller: bluehouseapp.controller.banedips:indexAction
      _bluehouseapp:
        sortable: true
        sorting:
            timestamp:  desc
        filterable: true
        criteria:
          status: true
      _format: ~

bluehouseapp_banedIPs_show:
    path:     /{id}/show.{_format}
    defaults: { _controller: bluehouseapp.controller.banedips:showAction, _format: ~ }


bluehouseapp_banedIPs_create:
    path:     /create
    defaults: { _controller: "bluehouseapp.controller.banedips:createAction" }


bluehouseapp_banedIPs_update:
    path:     /{id}/update
    defaults: { _controller: bluehouseapp.controller.banedips:updateAction }


bluehouseapp_banedIPs_delete:
    path:     /{id}/delete
    defaults: { _controller: "bluehouseapp.controller.banedips:deleteAction" }
