bluehouseapp_category_index:
    path:     /
    defaults:
      _controller: bluehouseapp.controller.category:indexAction
      _bluehouseapp:
        sortable: true
        sorting:
            id:  desc
        filterable: true
        criteria:
          status: true

bluehouseapp_category_show:
    path:     /{id}/show
    defaults: { _controller: "bluehouseapp.controller.category:showAction" }

bluehouseapp_category_new:
    path:     /new
    defaults: { _controller: "bluehouseapp.controller.category:createAction" }

bluehouseapp_category_create:
    path:     /create
    defaults: { _controller: "bluehouseapp.controller.category:createAction" }
    requirements: { _method: post }

bluehouseapp_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "bluehouseapp.controller.category:updateAction" }

bluehouseapp_category_update:
    path:     /{id}/update
    defaults: { _controller: "bluehouseapp.controller.category:updateAction" }
    requirements: { _method: post|put }

bluehouseapp_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "bluehouseapp.controller.category:deleteAction" }
    requirements: { _method: get|post|delete }

bluehouseapp_category_enable:
    path:    /enable/{id}
    defaults: { _controller: "bluehouseapp.controller.category:enableAction" }
bluehouseapp_category_disable:
    path:     /disable/{id}
    defaults: { _controller: "bluehouseapp.controller.category:disableAction" }