bluehouseapp_members_list:
    path:     /list
    defaults:
      _controller: bluehouseapp.controller.member:listAction
      sortable:  true
      sorting:
         id:  desc
bluehouseapp_member_enable:
    path:    /enable/{id}
    defaults: { _controller: "bluehouseapp.controller.member:enableAction" }
bluehouseapp_member_disable:
    path:     /disable/{id}
    defaults: { _controller: "bluehouseapp.controller.member:disableAction" }