bluehouseapp_audit:
    resource: @BluehouseappWebBundle/Resources/config/routing/backend/admin/audit.yml
    prefix: /audit
bluehouseapp_banedIPs:
    resource: @BluehouseappWebBundle/Resources/config/routing/backend/admin/banedIPs.yml
    prefix: /banedIPs
bluehouseapp_category:
    resource: @BluehouseappWebBundle/Resources/config/routing/backend/admin/category.yml
    prefix: /category
bluehouseapp_member:
    resource: @BluehouseappWebBundle/Resources/config/routing/backend/admin/member.yml
    prefix: /members
bluehouseapp_node:
    resource: @BluehouseappWebBundle/Resources/config/routing/backend/admin/node.yml
    prefix: /node